name: PowershellTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/powershell:${{ matrix.powershell-version }}-ubuntu-18.04

    strategy:
      matrix:
        powershell-version: [6.1.0, 7.0.0]

    steps:

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Pester
      run: |
        Install-Module Pester -Force
      shell: pwsh

    - name: Run Tests
      run: |
        ./src/PS-AutoApi.test/PS-AutoApi.ps1
      shell: pwsh
