name: PowershellTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        powershell-version: [5.1, 6, 7]

    steps:
    - name: Docker Checkout
      uses: docker://mcr.microsoft.com/powershell:${{ matrix.powershell-version }}-ubuntu-18.04

    # - name: Install dependencies
    #   run: |
    #     Install-Module Pester

    - name: Run Tests
      run: |
        .\src\PS-AutoApi.test\PS-AutoApi.ps1
