name: PowershellTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
        image: mcr.microsoft.com/powershell:${{ matrix.powershell-version }}-ubuntu-18.04

    strategy:
      matrix:
        powershell-version: [6.1.0, 7.0.0]

    steps:
    # - name: Docker Checkout
    #   uses: docker://mcr.microsoft.com/powershell:${{ matrix.powershell-version }}-ubuntu-18.04

    # - name: Install dependencies
    #   run: |
    #     Install-Module Pester

    - name: Run Tests
      run: |
        .\src\PS-AutoApi.test\PS-AutoApi.ps1
